Display spinner when doing an action on a volume
docker/volumes-backup-extension pull request #47
Opened 2022-08-24 14:17 UTC by felipecruz91

This PR allows performing multiple actions on different volumes without having to wait for the dialog to complete. It keeps the state so when users leave the extensions screen and come back, they can see what operations are still in progress and prevents them from doing any other action in the _same_ volume.

https://user-images.githubusercontent.com/15997951/186441920-67124329-455f-43cd-8366-17b1bc5a78e1.mov

TODO:

- [x] Display spinner for export/import/save/load.
- [ ] Display spinner for transfer.
- [ ] Display spinner for push/pull actions (there's a current limitation for this atm).
- [ ] Remove backdrop and auto-close dialogs when doing an action.

2022-08-25 09:51 UTC, gtardif reviewed
LGTM appart from the refresh of the spinner once the export is finished, as discussed with @felipecruz91

2022-08-26 09:22 UTC, lucbpz commented
Huge change and nice improvements! A couple of things I noticed:
- **Clone** and **Delete** actions don't use the same UX pattern - we should have the same pattern for every action, and these two haven't changed to the new one.
  - With the new pattern, we unmount the component right after the button is clicked, so every error handler needs to be attached to the Promise instead of doing a 'try catch' block in order to work.
- Inside the action execution functions (export, etc) I would remove the `async` `await`s when it's not needed instead of executing the `onClose` at the beginning of the functions. This works, but makes it unclear what are the dev intentions within the scope.
- The UI when we display the loading state for every row can be improved (it doesn't need to be a `GridActionsCellItem` as it's going to wrap everything into a rounded button

2022-08-26 09:24 UTC, lucbpz requested changes
Huge change and nice improvements! A couple of things I noticed:

- **Clone** and **Delete** actions don't use the same UX pattern - we should have the same pattern for every action, and these two haven't changed to the new one.
  - With the new pattern, we unmount the component right after the button is clicked, so every error handler needs to be attached to the Promise instead of doing a 'try catch' block in order to work.
- Inside the action execution functions (export, etc) I would remove the `async` `await`s when it's not needed instead of executing the `onClose` at the beginning of the functions. This works, but makes it unclear what are the dev intentions within the scope.
- The UI when we display the loading state for every row can be improved (it doesn't need to be a `GridActionsCellItem` as it's going to wrap everything into a rounded button.

2022-08-26 14:34 UTC, lucbpz approved these changes

2022-08-26 14:34 UTC, merged