Improve volume list performance
docker/volumes-backup-extension pull request #62
Opened 2022-09-10 12:20 UTC by felipecruz91

2022-09-13 16:15 UTC, benja-M-1 commented
I haven't tested it yet. But from the video I see that every sizes are recalculated when one volume is added. Is there any reason to not only calculate the size of the newly added volume instead?

2022-09-13 16:54 UTC, benja-M-1 approved these changes
Other than [that](https://github.com/docker/volumes-backup-extension/pull/62#issuecomment-1245640021) I tested it and it works fine

2022-09-14 11:58 UTC, felipecruz91 commented
Thank you @benja-M-1 for your valuable feedback! If you try the extension again, it shouldn't recalculate all the volumes size when cloning or deleting a volume.

2022-09-15 07:39 UTC, lucbpz requested changes

2022-09-15 07:39 UTC, lucbpz commented on ui/src/App.tsx
> +  const handleImportIntoNewDialogCompletion = (
Can we reuse the `onClose` functions instead of passing another callback?

2022-09-15 07:42 UTC, lucbpz approved these changes

2022-09-15 07:55 UTC, merged