feat(): add ux improvements
docker/volumes-backup-extension pull request #80
Opened 2022-09-19 12:43 UTC by lucbpz

Address all UX improvements from our design team.

2022-09-19 13:19 UTC, felipecruz91 reviewed
After emptying the volume, the size needs to be recalculated (or set it to 0 directly if the empty action was successful).

2022-09-19 14:44 UTC, gtardif approved these changes
LGTM appart from @felipecruz91 comment on empty volume action (well spotted! )

2022-09-19 15:11 UTC, lucbpz commented on ui/src/App.tsx
> +                  // openDialog={() => setOpenImportIntoNewDialog(true)}
done!

2022-09-20 09:50 UTC, felipecruz91 commented
Added the following request to this PR too:

- https://github.com/docker/volumes-backup-extension/issues/67

2022-09-20 12:42 UTC, gtardif requested changes
Need to fix MUI license watermark. This can be tested by installing the extension build for this PR in the CI, it should normally have the secret license key

2022-09-20 13:50 UTC, felipecruz91 commented on .github/workflows/build-scan-push.yaml
> +#          cache-to: type=gha,mode=max
@gtardif The issue with the license key was that the stage was cached, now it works fine:

![image](https://user-images.githubusercontent.com/15997951/191275664-ab73b957-9004-4a1d-9a9a-6a65354a1638.png)

2022-09-20 13:51 UTC, felipecruz91 commented on .github/workflows/build-scan-push.yaml
> +#          cache-to: type=gha,mode=max
Undo:

```suggestion
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
```

2022-09-20 14:52 UTC, felipecruz91 commented
@gtardif LGTM

![image](https://user-images.githubusercontent.com/15997951/191291305-2bb0ba8f-0b31-4822-b6de-d1abd4f16324.png)

2022-09-20 14:53 UTC, merged